force-app/main/default/objects/CEC_Case_Supplementary_Data__c/CEC_Case_Supplementary_Data__c.object-meta.xml
<CustomObject>
    <description>This object will be a lookup to a Case, and will contain data for the field which are specific to the country/business unit/category/sub category for that case.</description>
    <label>Case Supplementary Data</label>
    <nameField>
        <displayFormat>CSD{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Supplementary Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CEC_Case_Supplementary_Data__c/fields/CEC_Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>CEC_Parent_Case__c</fullName>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Supplementary Data</relationshipLabel>
    <relationshipName>Case_Supplementary_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Context_Mapping__mdt/CEC_Country_Context_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>CEC Country Context Mapping</label>
    <pluralLabel>CEC Country Context Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEC_Country_Context_Mapping__mdt/fields/CEC_City__c.field-meta.xml
<CustomField>
    <fullName>CEC_City__c</fullName>
    <defaultValue>false</defaultValue>
    <label>City</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Context_Mapping__mdt/fields/CEC_Context__c.field-meta.xml
<CustomField>
    <fullName>CEC_Context__c</fullName>
    <label>Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-Account Business</fullName>
                <default>true</default>
                <label>Non-Account Business</label>
            </value>
            <value>
                <fullName>Assistance Required</fullName>
            </value>
            <value>
                <fullName>Third-Party Auditor</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEC_Country_Context_Mapping__mdt/fields/CEC_Country_Mapping__c.field-meta.xml
<CustomField>
    <fullName>CEC_Country_Mapping__c</fullName>
    <label>CEC Country Mapping</label>
    <referenceTo>CEC_Country_Mapping__mdt</referenceTo>
    <relationshipLabel>CEC Country Context Mappings</relationshipLabel>
    <relationshipName>CEC_Country_Context_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Context_Mapping__mdt/fields/CEC_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>CEC_PostalCode__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PostalCode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Context_Mapping__mdt/fields/CEC_State__c.field-meta.xml
<CustomField>
    <fullName>CEC_State__c</fullName>
    <defaultValue>false</defaultValue>
    <label>State</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Context_Mapping__mdt/fields/CEC_Street__c.field-meta.xml
<CustomField>
    <fullName>CEC_Street__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Street</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Mapping__mdt/CEC_Country_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>CEC Country Mapping</label>
    <pluralLabel>CEC Country Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEC_Country_Mapping__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <defaultValue>false</defaultValue>
    <label>City</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Mapping__mdt/fields/Country_ISO2Code__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO2Code__c</fullName>
    <label>Country ISO2Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEC_Country_Mapping__mdt/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Postal Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DynamicFieldCaseHandler.cls
public with sharing class DynamicFieldCaseHandler {
    public DynamicFieldCaseHandler() {

    }

    @AuraEnabled(cacheable=true)
    public static CEC_Case_Supplementary_Data__c getSupplementaryData(Id recordId,List<string> fields){
        List<CEC_Case_Supplementary_Data__c> cS1 = new List<CEC_Case_Supplementary_Data__c>();
        string query = 'SELECT ID,';
        for(string fld : fields){
            query += fld + ', ';
        } 

        query += 'FROM CEC_Case_Supplementary_Data__c where CEC_Parent_Case__c =: recordId LIMIT 1';

        List<sObject> sObjList = Database.query(query);
        for(Object obj : sObjList){
            CEC_Case_Supplementary_Data__c cS = new CEC_Case_Supplementary_Data__c();
            cS = (CEC_Case_Supplementary_Data__c)obj;
            cS1.add(cs);
        }

        if(!cS1.isEmpty()){
            return cS1[0];
        }return null;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String,Object> getSupplementaryFieldsFromRouting(String cntry,string bUnit){
        List<Routing_Table__c> rTable = [SELECT Id, Name, Business_Unit__c, Country__c,Supplementary_Fields__c
         FROM Routing_Table__c where Country__c =: cntry AND Business_Unit__c =: bUnit];
        
        String dynamicfieldsJson;       
        if(!rTable.isEmpty()){
            dynamicfieldsJson=rTable[0].Supplementary_Fields__c;
        }
        if(dynamicfieldsJson != null){
            Map<String,Object> dynamicf= (Map<String,Object>)JSON.deserializeUntyped(dynamicfieldsJson);
            List<Map<String, Object>> dynamicfields = new List<Map<String, Object>>();
            List<Object> myMapObjects = (List<Object>) dynamicf.get('result');
            for (Object obj : myMapObjects) {
                dynamicfields.add((Map<String, Object>)obj);
            }
            SObjectType arInstructionType = Schema.getGlobalDescribe().get('CEC_Case_Supplementary_Data__c');
            Map<String,Schema.SObjectField> fieldMap = arInstructionType.getDescribe().fields.getMap();
            map<string,Map<String,Object>> dynamicFieldsOptions= new map<string,Map<String,Object>>();
            for(Map<String,Object> dynamicfield:dynamicfields){
                if(dynamicfield.containskey('Name')) {
                Schema.SObjectField field = fieldMap.get(string.valueOf(dynamicfield.get('Name')));
                List<Object> options= new List<Object>();
                List<Schema.PicklistEntry> ple = field.getDescribe().getPicklistValues();
                if(field.getDescribe().getPicklistValues() != null){
                    for( Schema.PicklistEntry f : ple){
                        options.add(new Map<String,Object>{'label'=>f.getLabel(),'value'=>f.getValue()});
                    }
                    dynamicFieldsOptions.put(string.valueof(dynamicfield.get('Name')),new Map<String,Object>{'values'=>options});
                }
            }
            }
            return new Map<String,Object>{
                'dynamicFields'=>dynamicfields,'picklistFieldValues'=>dynamicFieldsOptions
                    }; 
         }
        return null;
    }
      /**
    * @description: 1692293-Phone Numbers in Appropriate Country Format 
    * @author PS 
    * @return List<CEC_Country_Mapping__mdt> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<CEC_Country_Mapping__mdt> getCountryMappingDetails() {
        return [Select DeveloperName, MasterLabel, Label,Country_ISO2Code__c,Postal_Code__c,City__c,
                (Select Id,CEC_City__c,CEC_Context__c,CEC_PostalCode__c,CEC_State__c,CEC_Street__c From CEC_Country_Context_Mappings__r) 
                From CEC_Country_Mapping__mdt order by MasterLabel asc]; 
    }

     /**
    * @description: 1692293-Phone Numbers in Appropriate Country Format 
    * @author PS 
    * @return List<CEC_Country_Mapping__mdt> 
    **/
    @AuraEnabled(cacheable=true)
    public static Map<String,CEC_Exceptional_Country__mdt> getExceptionalCountryMappingDetails() {
        Map<String,CEC_Exceptional_Country__mdt>  exceptionalCountryMap = new Map<String,CEC_Exceptional_Country__mdt> ();


        List<CEC_Exceptional_Country__mdt>  exceptionalCountryList = [Select CEC_Country_Label__c, CEC_Country_ExceptionalLabel__c, CEC_Country_ISO2Code__c
                From CEC_Exceptional_Country__mdt order by MasterLabel asc]; 

        for (CEC_Exceptional_Country__mdt exceptionalCountry : exceptionalCountryList) {
            exceptionalCountryMap.put(exceptionalCountry.CEC_Country_Label__c,exceptionalCountry);
        }
        return exceptionalCountryMap;
    }
}